# Change these first
owner: torrentpier # Your GitHub organization or username, where this repository lives
repo: uptime-sites # The name of this repository

sites:
  - name: TorrentPier
    url: https://torrentpier.com
  - name: TorrentPier Demo
    url: https://torrentpier.duckdns.org/
  - name: Get TorrentPier
    url: https://get-torrentpier.duckdns.org
  - name: TorrentPier Archive
    url: https://archive-torrentpier.duckdns.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /$REPO
  logoUrl: https://raw.githubusercontent.com/torrentpier/torrentpier/master/styles/images/logo/logo.png
  name: TorrentPier Sites Status
  introTitle: Latest Updates
  introMessage: Site to announce any maintenance and the current status of TorrentPier sites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
